version: "3.8"

services:
  dam:
    image: "salmon_dam"
    build: ./dam
    networks:
      - ocean

  river:
    image: "salmon_river"
    build: ./river
    networks:
      - ocean

  nginx:
    image: "salmon_nginx"
    build: ./nginx
    networks:
      - ocean
    ports:
      - "9999:80"

networks:
 ocean:
